sudo: required

env:
  - VERSION=2.8
  - VERSION=3.0
  - VERSION=3.2

services:
  - docker

before_install:
  - sudo apt-get -y install python-pip
  - sudo pip install docker-squash
  - docker build -t nanobox/redis:$VERSION ./$VERSION

script: sudo test/run_all.sh $VERSION

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - "echo \"Branch: '$BRANCH'; Version: '$VERSION'\";"
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker build -t ${NAMESPACE}/redis ./${VERSION};
  - docker-squash -t ${NAMESPACE}/redis:squashed -f nanobox/runit --tmp-dir /var/tmp/squasher ${NAMESPACE}/redis
  # `$VERSION-beta` tag is always pushed (master or any dev branch)
  - docker tag ${NAMESPACE}/redis:squashed ${NAMESPACE}/redis:${VERSION}-beta;
  - docker push ${REMOTE}${NAMESPACE}/redis:${VERSION}-beta;
  # `beta` tag is always pushed (master or any dev branch)
  - if [ "$VERSION" == "3.0" ]; then
    docker tag ${NAMESPACE}/redis:squashed ${NAMESPACE}/redis:beta;
    docker push ${REMOTE}${NAMESPACE}/redis:beta;
    fi
  # `latest` tag is only pushed on master && most recent version
  - if [ "$BRANCH" == "master" ] && [ "$VERSION" == "3.0" ]; then
    docker tag ${NAMESPACE}/redis:squashed ${NAMESPACE}/redis;
    docker push ${REMOTE}${NAMESPACE}/redis;
    fi
  # `$VERSION` (latest/stable implied) tag is only pushed on master. tag branch for clarity otherwise (`$VERSION-$BRANCH`)
  - if [ "$BRANCH" == "master" ]; then
    docker tag ${NAMESPACE}/redis:squashed ${NAMESPACE}/redis:${VERSION};
    docker push ${REMOTE}${NAMESPACE}/redis:${VERSION};
    else
    docker tag ${NAMESPACE}/redis:squashed ${NAMESPACE}/redis:${VERSION}-${BRANCH//\//_};
    docker push ${REMOTE}${NAMESPACE}/redis:${VERSION}-${BRANCH//\//_};
    fi
